def exceptions(): 
    return 0